obj-$(CONFIG_MCU_SPI) += mcu-spi.o
obj-$(CONFIG_SPI_IMX_SHAPER) += spi-imx-shaper.o
obj-$(CONFIG_REMOTEPROC_SHAPER) += shaper-rproc.o
obj-$(CONFIG_SHAPER_MCU_TTY_SHAPER) += shaper-tty.o
obj-$(CONFIG_SHAPER_MCU_LOG) += shaper-mcu-log.o
obj-$(CONFIG_SHAPER_MCU_CAPTURE) += shaper-mcu-capture.o

obj-$(CONFIG_SHAPER_MCU_SPACES) += shaper-mcu-spaces.o
shaper-mcu-spaces-y := spaces-core.o
shaper-mcu-spaces-y += spaces-dev-file.o
shaper-mcu-spaces-y += spaces-pdev-file.o
shaper-mcu-spaces-y += space-descriptor.o
shaper-mcu-spaces-y += capnp/capn.o
shaper-mcu-spaces-y += capnp/capn-malloc.o
shaper-mcu-spaces-y += capnp/capn-stream.o
shaper-mcu-spaces-y += capnp/mcu-descriptor-capnp.o
